'use server'

import { createClient } from '@/lib/supabase/server'
import { createAdminClient } from '@/lib/supabase/admin'
import { inviteSchema } from '@/lib/validations/auth'
import { headers } from 'next/headers'

type SendInviteInput = {
  email: string
  orgId: string
}

type SendInviteResult = {
  success?: boolean
  inviteLink?: string
  error?: string
}

export async function sendInvite(
  input: SendInviteInput
): Promise<SendInviteResult> {
  // Validate email
  const parsed = inviteSchema.safeParse({ email: input.email })
  if (!parsed.success) {
    return { error: 'Email invalido.' }
  }

  const supabase = await createClient()

  // Verify authenticated user
  const {
    data: { user },
  } = await supabase.auth.getUser()

  if (!user) {
    return { error: 'No autenticado.' }
  }

  // Verify user is a member of the org
  const activeOrgId = user.app_metadata?.org_id
  if (!activeOrgId || activeOrgId !== input.orgId) {
    return { error: 'No tienes permisos para invitar miembros a esta organizacion.' }
  }

  // Check if email is already a member
  const admin = createAdminClient()

  // Check for existing pending invite
  const { data: existingInvite } = await admin
    .from('org_invites')
    .select('id')
    .eq('org_id', input.orgId)
    .eq('email', parsed.data.email)
    .is('accepted_at', null)
    .gt('expires_at', new Date().toISOString())
    .single()

  if (existingInvite) {
    return { error: 'Ya existe una invitacion pendiente para este email.' }
  }

  // Insert invite -- token and expires_at are auto-generated by DB defaults
  const { data: invite, error: insertError } = await admin
    .from('org_invites')
    .insert({
      org_id: input.orgId,
      email: parsed.data.email,
      invited_by: user.id,
    })
    .select('token')
    .single()

  if (insertError || !invite) {
    return { error: 'No se pudo enviar la invitacion. Intenta de nuevo.' }
  }

  // Construct invite link
  const headersList = await headers()
  const host = headersList.get('host') ?? 'localhost:3000'
  const protocol = headersList.get('x-forwarded-proto') ?? 'http'
  const origin = `${protocol}://${host}`
  const inviteLink = `${origin}/api/invites/accept?token=${invite.token}`

  return { success: true, inviteLink }
}
